# Generated by Django 4.0.6 on 2022-07-30 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190720_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBoardPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(max_length=11, unique=True)),
                ('boardpostid', models.IntegerField(max_length=11, unique=True)),
                ('good', models.IntegerField(default=0)),
                ('bad', models.IntegerField(default=0)),
            ],
        ),
    ]
